"""The typed run-configuration schema.

Frozen dataclasses that name every run parameter once (its default and its validation) and feed
the provenance that the on-image stamp, the volume artifact, and the end-of-run summary all read.
The CLI populates them from ``--flags``; a YAML or GUI loader would be just another front-end
constructing the same dataclasses.
"""

from __future__ import annotations

from qorona.config.schema import (
    ANNOTATE_POSITIONS,
    BRIGHTNESS_FRAMES,
    BRIGHTNESS_OCCULT_MODES,
    BRIGHTNESS_SCALINGS,
    BRIGHTNESS_VIGNETTES,
    CLOSED_TREATMENTS,
    DEVICE_MODES,
    DISPLAY_MODES,
    EXPORT_FORMATS,
    FIELDLINE_COLOUR,
    FIELDLINE_SEEDING,
    FIELDLINE_SHOW,
    OCCULT_MODES,
    POLARITY_MODES,
    PRECISION_MODES,
    QMAP_EXPORT_FORMATS,
    QUALITY_PRESETS,
    RENDER_EXPORT_FORMATS,
    RESAMPLERS,
    SPACING_LAWS,
    THOMSON_MODES,
    VOLUME_BUILDERS,
    WEIGHTING_PRESETS,
    BrightnessConfig,
    CameraConfig,
    ExportConfig,
    FieldLinesConfig,
    GridConfig,
    InputConfig,
    OutputConfig,
    QMapConfig,
    RenderConfig,
    RunConfig,
    ThomsonConfig,
    VolumeConfig,
    WeightingConfig,
)

__all__ = [
    "ANNOTATE_POSITIONS",
    "BRIGHTNESS_FRAMES",
    "BRIGHTNESS_OCCULT_MODES",
    "BRIGHTNESS_SCALINGS",
    "BRIGHTNESS_VIGNETTES",
    "CLOSED_TREATMENTS",
    "DEVICE_MODES",
    "DISPLAY_MODES",
    "EXPORT_FORMATS",
    "FIELDLINE_COLOUR",
    "FIELDLINE_SEEDING",
    "FIELDLINE_SHOW",
    "OCCULT_MODES",
    "POLARITY_MODES",
    "PRECISION_MODES",
    "QMAP_EXPORT_FORMATS",
    "QUALITY_PRESETS",
    "RENDER_EXPORT_FORMATS",
    "RESAMPLERS",
    "SPACING_LAWS",
    "THOMSON_MODES",
    "VOLUME_BUILDERS",
    "WEIGHTING_PRESETS",
    "BrightnessConfig",
    "CameraConfig",
    "ExportConfig",
    "FieldLinesConfig",
    "GridConfig",
    "InputConfig",
    "OutputConfig",
    "QMapConfig",
    "RenderConfig",
    "RunConfig",
    "ThomsonConfig",
    "VolumeConfig",
    "WeightingConfig",
]
